### ISSUE TITLE
Fails to compile with current version of minigrace

### ISSUE THREAD

**Issue by petercowal** [gracelang/objectdraw#20] opened 2016-07-07 19:59 UTC
When building minigrace, the make script fails after trying to compile objectdraw, with the following error:
```
objectdraw.grace[56:13-17]: Syntax error: Point is both inherited, and defined in an enclosing scope.
  55:     // The size (width, height) of this component
  56:     size -> Point
------------------^^^^^
```

**Comment by apblack** [comment] 2016-07-07 20:08
I thought that I had fixed this issue, but see that I have not committed the fix.  It may be on Sly, watiing to be committed.

The problem is that objectdraw both inherits the methods of StandardPrelude, and gets them because it uses the StandardPRelude as a prelude.  Thus, `Point` is both inherited and available in an outer scope.  The simplest fix is to declare 

    type Point = prelude.Point

If you look at ~black/Development/mg/apb/minigrace/objectdraw.grace on sly.cs.pdx.edu, I think that you will find a modified version.

**Comment by apblack** [comment] 2016-08-02 00:40
Fix has been committed; it was in branch ambigNames.

**Closed by apblack** 2016-08-02 00:40 UTC
