### ISSUE TITLE
KeyPress events broken

### ISSUE THREAD

**Issue by KimBruce** [gracelang/objectdraw#24] opened 2016-08-31 04:27 UTC
Key events no longer function correctly in objectdraw.  Here is a very simple sample program that simply prints out the code associated with each key pressed:
```
dialect "objectdraw"

def keyDemo: GraphicApplication = object {
  inherit graphicApplicationSize (300 @ 300)
  
  onKeyPressDo{keyEvt: KeyEvent ->
     print (keyEvt.code)
  }
  
  startGraphics
}
```

This blows up with the following error message:

```
NoSuchMethod on line 0 of objectdraw: no method 'eventSource(_)$object(_)' on the "testrt" module.
  raised at module.eventSource(_)$object(_) in objectdraw
  called from keyDemo.keyEventSource(_)event(_) at line 661 of objectdraw
  called from execution environment.
   1: #pragma ExtendedLineups
```
I can't figure out where the method eventSource()$object comes in.  It does not appear in objectdraw, though eventSource does.  On the other hand objectdraw.js includes a comment referring to this method on line 240.

Events on buttons and pop-up menus appear to work fine, so I am puzzled as to what the problem is here.  Suggestions on interpreting the error message (esp. where the method name comes from)?

**Comment by petercowal** [comment] 2016-09-01 21:51
I experimented a bit and found that attempting to invoke a mouse event results in an error message as well (though without the `$object` tag; I think that `$object` is automatically added to handle constructors differently somehow...).  

The method call
```
onMousePressDo { m →
     print ("Hi!")
  }
```
results in the error message
```
NoSuchMethod on line 568 of objectdraw: no method 'mouseEventSource(_)event(_)' on the "keytest" module.
  raised at module.mouseEventSource(_)event(_) at line 568 of objectdraw
  called from execution environment.
 567:         on (kind) do { event' ->
 568:             f.apply (mouseEventSource (self) event (event'))
 569:         }
```

However, overriding the `onMousePress` method
```
method onMousePress (m) {
   print ("Hi!")
}
```
works as expected, so the error appears to stem from somewhere in the event handling code for the `on*PressDo` methods.

**Comment by apblack** [comment] 2016-09-01 22:42
This seems to be a _minigrace_ inheritance problem, rather than something specific to _objectdraw_.

As @petercowal says, the fake method `eventSource(_)$object(_)` is created for use when inheriting from `eventSource(_)`.   Since the semantics of an object after the keyword `inherit` is different from that semantics of that object in ordinary contexts, we generate special code to create it.   Michael had the smart idea of using the keyword `object` as part of the method name, so that this method could not possibly be declared by user code; it also hints at the purpose of the additional parameter, which is to reference the object that will be mutated by this constructor.

I'm puzzled by the error, though, since the `eventSource(_)$object(_)` method does indeed exist, as you verified by looking at the generated JavaScript.  I'll see if I can reproduce it.

**Comment by apblack** [comment] 2016-09-01 23:34
It's the `outer` problem again.  The method `eventSource(_)$object(_)` is being requested on the _keytest_ module, whereas it should be requested on the _objectdraw_ module.  

I'm in the process of trying to replace the implementation of `outer` with one that works, i.e., lexical binding.    I don't know any other way of fixing this.

**Comment by apblack** [comment] 2016-09-05 05:56
I realized on Saturday that I could implement a "quick" hack that might get this stuff working again while I move ahead with a real solution for outer.  References to module objects need not be compiled as a sequence of `outer`s, but can be turned into static references, since modules are singleton objects.

This is now committed in the minigrace master branch, and is running on http://www.cs.pdx.edu/~black/ide.  This program now works:

```grace
dialect "objectdraw"

def keyDemo: GraphicApplication = object {
    inherit graphicApplicationSize (300 @ 300)

    onKeyPressDo{keyEvt: KeyEvent ->
        print("key code={keyEvt.code}, " ++
              "char={keyEvt.character}, " ++
              "shifted={keyEvt.shiftKey}, " ++
              "ctrled={keyEvt.ctrlKey}, " ++
              "alt'ed={keyEvt.altKey}, " ++
              "meta'ed={keyEvt.metaKey}")
    }
    
    onMouseClickDo{mouseEvt: MouseEvent →
        print "click at {mouseEvt.at}"
    }

    startGraphics
}
```
Check it out and see if it works for you.  The change is quite pervasive, so it's hard to forsee all the consequences.  Once again, I urge you to take a little time to create a test suite for objectdraw; this would help to prevent ongoing evolution from breaking things without my noticing.  I have no idea why key events used to work and then stopped working.

**Closed by apblack** 2016-09-05 05:56 UTC
